version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: GAME_DB  # 데이터베이스 이름
      POSTGRES_USER: GAME_USER    # 사용자 이름
      POSTGRES_PASSWORD: gamecenter  # 사용자 비밀번호
    ports:
      - "15432:5432"  # 호스트 포트:컨테이너 포트
    volumes:
      - C:/leejunbum/docker/postgres/data:/var/lib/mysql:rw  # 데이터 볼륨 마운트